import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddEstadosDiscapacidades20260115120000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    // Crear tabla NET_DISCAPACIDADES
    await queryRunner.query(`
      CREATE TABLE "NET_DISCAPACIDADES" (
        "ID_DISCAPACIDAD" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE,
        "NOMBRE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
        "DESCRIPCION" VARCHAR2(400 BYTE),
        CONSTRAINT "PK_NET_DISCAPACIDADES" PRIMARY KEY ("ID_DISCAPACIDAD")
      )
    `);

    await queryRunner.query(`
      CREATE INDEX "IDX_DISCAPACIDADES_NOMBRE" ON "NET_DISCAPACIDADES" ("NOMBRE")
    `);

    // Crear tabla NET_ESTADOS
    await queryRunner.query(`
      CREATE TABLE "NET_ESTADOS" (
        "ID_ESTADO" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE,
        "NOMBRE_ESTADO" VARCHAR2(50 BYTE) NOT NULL ENABLE,
        "DESCRIPCION" VARCHAR2(200 BYTE),
        "CLASIFICACION" VARCHAR2(20 BYTE) NOT NULL ENABLE,
        CONSTRAINT "PK_NET_ESTADOS" PRIMARY KEY ("ID_ESTADO")
      )
    `);

    await queryRunner.query(`
      CREATE INDEX "IDX_ESTADOS_CLASIFICACION" ON "NET_ESTADOS" ("CLASIFICACION")
    `);

    await queryRunner.query(`
      CREATE INDEX "IDX_ESTADOS_NOMBRE" ON "NET_ESTADOS" ("NOMBRE_ESTADO")
    `);

    // Semillas de estados de EVENTO
    await queryRunner.query(`
      INSERT INTO "NET_ESTADOS" ("NOMBRE_ESTADO", "DESCRIPCION", "CLASIFICACION") VALUES ('Activo', 'Evento activo', 'EVENTO')
    `);
    await queryRunner.query(`
      INSERT INTO "NET_ESTADOS" ("NOMBRE_ESTADO", "DESCRIPCION", "CLASIFICACION") VALUES ('Reprogramado', 'Evento reprogramado', 'EVENTO')
    `);
    await queryRunner.query(`
      INSERT INTO "NET_ESTADOS" ("NOMBRE_ESTADO", "DESCRIPCION", "CLASIFICACION") VALUES ('Finalizado', 'Evento finalizado', 'EVENTO')
    `);

    // Semillas de estados de DOCENTE
    await queryRunner.query(`
      INSERT INTO "NET_ESTADOS" ("NOMBRE_ESTADO", "DESCRIPCION", "CLASIFICACION") VALUES ('Inscrito', 'Docente inscrito', 'DOCENTE')
    `);
    await queryRunner.query(`
      INSERT INTO "NET_ESTADOS" ("NOMBRE_ESTADO", "DESCRIPCION", "CLASIFICACION") VALUES ('En espera', 'Docente en espera', 'DOCENTE')
    `);
    await queryRunner.query(`
      INSERT INTO "NET_ESTADOS" ("NOMBRE_ESTADO", "DESCRIPCION", "CLASIFICACION") VALUES ('Cancelado', 'Docente cancelado', 'DOCENTE')
    `);

    // Alter NET_DOCENTE: agregar columnas ASISTIO, PENALIZADO, ID_DISCAPACIDAD
    await queryRunner.query(`
      ALTER TABLE "NET_DOCENTE" ADD ("ASISTIO" VARCHAR2(2 BYTE) DEFAULT 'NO')
    `);
    await queryRunner.query(`
      ALTER TABLE "NET_DOCENTE" ADD ("PENALIZADO" VARCHAR2(2 BYTE) DEFAULT 'NO')
    `);
    await queryRunner.query(`
      ALTER TABLE "NET_DOCENTE" ADD ("ID_DISCAPACIDAD" NUMBER)
    `);
    await queryRunner.query(`
      CREATE INDEX "IDX_DOCENTE_DISCAPACIDAD" ON "NET_DOCENTE" ("ID_DISCAPACIDAD")
    `);

    await queryRunner.query(`
      ALTER TABLE "NET_DOCENTE" ADD CONSTRAINT "FK_DOCENTE_DISCAPACIDAD" FOREIGN KEY ("ID_DISCAPACIDAD") REFERENCES "NET_DISCAPACIDADES" ("ID_DISCAPACIDAD")
    `);

    // Alter NET_REGISTRO_EVENTOS: agregar ID_ESTADO, CANTIDAD_INV_DOCENTE
    await queryRunner.query(`
      ALTER TABLE "NET_REGISTRO_EVENTOS" ADD ("ID_ESTADO" NUMBER)
    `);
    await queryRunner.query(`
      ALTER TABLE "NET_REGISTRO_EVENTOS" ADD ("CANTIDAD_INV_DOCENTE" NUMBER)
    `);
    await queryRunner.query(`
      CREATE INDEX "IDX_REGISTRO_ESTADO" ON "NET_REGISTRO_EVENTOS" ("ID_ESTADO")
    `);
    await queryRunner.query(`
      ALTER TABLE "NET_REGISTRO_EVENTOS" ADD CONSTRAINT "FK_REGISTRO_ESTADO" FOREIGN KEY ("ID_ESTADO") REFERENCES "NET_ESTADOS" ("ID_ESTADO")
    `);

    // Alter NET_EVENTOS: agregar CANTIDAD_INV_PERMITIDOS
    await queryRunner.query(`
      ALTER TABLE "NET_EVENTOS" ADD ("CANTIDAD_INV_PERMITIDOS" NUMBER)
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Revertir cambios de NET_EVENTOS
    await queryRunner.query(`
      ALTER TABLE "NET_EVENTOS" DROP COLUMN "CANTIDAD_INV_PERMITIDOS"
    `);

    // Revertir cambios de NET_REGISTRO_EVENTOS
    await queryRunner.query(`
      ALTER TABLE "NET_REGISTRO_EVENTOS" DROP CONSTRAINT "FK_REGISTRO_ESTADO"
    `);
    await queryRunner.query(`
      DROP INDEX "IDX_REGISTRO_ESTADO"
    `);
    await queryRunner.query(`
      ALTER TABLE "NET_REGISTRO_EVENTOS" DROP COLUMN "CANTIDAD_INV_DOCENTE"
    `);
    await queryRunner.query(`
      ALTER TABLE "NET_REGISTRO_EVENTOS" DROP COLUMN "ID_ESTADO"
    `);

    // Revertir cambios de NET_DOCENTE
    await queryRunner.query(`
      ALTER TABLE "NET_DOCENTE" DROP CONSTRAINT "FK_DOCENTE_DISCAPACIDAD"
    `);
    await queryRunner.query(`
      DROP INDEX "IDX_DOCENTE_DISCAPACIDAD"
    `);
    await queryRunner.query(`
      ALTER TABLE "NET_DOCENTE" DROP COLUMN "ID_DISCAPACIDAD"
    `);
    await queryRunner.query(`
      ALTER TABLE "NET_DOCENTE" DROP COLUMN "PENALIZADO"
    `);
    await queryRunner.query(`
      ALTER TABLE "NET_DOCENTE" DROP COLUMN "ASISTIO"
    `);

    // Borrar estados sembrados y tablas NET_ESTADOS y NET_DISCAPACIDADES
    await queryRunner.query(`
      DROP INDEX "IDX_ESTADOS_NOMBRE"
    `);
    await queryRunner.query(`
      DROP INDEX "IDX_ESTADOS_CLASIFICACION"
    `);
    await queryRunner.query(`
      DROP TABLE "NET_ESTADOS"
    `);

    await queryRunner.query(`
      DROP INDEX "IDX_DISCAPACIDADES_NOMBRE"
    `);
    await queryRunner.query(`
      DROP TABLE "NET_DISCAPACIDADES"
    `);
  }
}
