import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddIdToDocenteDiscapacidades20260116093000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    // Agregar columna identidad y cambiar PK
    await queryRunner.query(`
      ALTER TABLE "NET_DOCENTE_DISCAPACIDADES" ADD ("ID_DOCENTE_DISCAPACIDADES" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE)
    `);

    // Eliminar PK compuesta previa
    await queryRunner.query(`
      ALTER TABLE "NET_DOCENTE_DISCAPACIDADES" DROP CONSTRAINT "PK_NET_DOCENTE_DISCAPACIDADES"
    `);

    // Crear nueva PK por el ID
    await queryRunner.query(`
      ALTER TABLE "NET_DOCENTE_DISCAPACIDADES" ADD CONSTRAINT "PK_NET_DOCENTE_DISCAPACIDADES" PRIMARY KEY ("ID_DOCENTE_DISCAPACIDADES")
    `);

    // Asegurar unicidad del par (ID_PERSONA, ID_DISCAPACIDAD)
    await queryRunner.query(`
      ALTER TABLE "NET_DOCENTE_DISCAPACIDADES" ADD CONSTRAINT "UQ_DD_PERSONA_DISCAP" UNIQUE ("ID_PERSONA","ID_DISCAPACIDAD")
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Quitar la unicidad del par
    await queryRunner.query(`
      ALTER TABLE "NET_DOCENTE_DISCAPACIDADES" DROP CONSTRAINT "UQ_DD_PERSONA_DISCAP"
    `);

    // Quitar la PK por ID y restaurar PK compuesta
    await queryRunner.query(`
      ALTER TABLE "NET_DOCENTE_DISCAPACIDADES" DROP CONSTRAINT "PK_NET_DOCENTE_DISCAPACIDADES"
    `);

    await queryRunner.query(`
      ALTER TABLE "NET_DOCENTE_DISCAPACIDADES" ADD CONSTRAINT "PK_NET_DOCENTE_DISCAPACIDADES" PRIMARY KEY ("ID_PERSONA","ID_DISCAPACIDAD")
    `);

    // Eliminar la columna de identidad
    await queryRunner.query(`
      ALTER TABLE "NET_DOCENTE_DISCAPACIDADES" DROP COLUMN "ID_DOCENTE_DISCAPACIDADES"
    `);
  }
}
