import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateUsuarioEmpleado20260116110000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "NET_EMPLEADO" (
        "ID_EMPLEADO" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE,
        "NOMBRE" VARCHAR2(150) NOT NULL,
        "NUMERO_EMPLEADO" VARCHAR2(40) NOT NULL,
        "DNI" VARCHAR2(20) NOT NULL,
        "ID_AREA" NUMBER NOT NULL,
        CONSTRAINT "PK_NET_EMPLEADO" PRIMARY KEY ("ID_EMPLEADO")
      )
    `);

    await queryRunner.query(`
      ALTER TABLE "NET_EMPLEADO"
      ADD CONSTRAINT "FK_EMPLEADO_AREA" FOREIGN KEY ("ID_AREA")
      REFERENCES "NET_AREAS" ("ID_AREA")
    `);

    await queryRunner.query(`
      CREATE TABLE "NET_USUARIO" (
        "ID_USUARIO" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE,
        "CORREO_ELECTRONICO" VARCHAR2(150) NOT NULL,
        "CONTRASENA" VARCHAR2(200) NOT NULL,
        "ID_EMPLEADO" NUMBER NOT NULL,
        CONSTRAINT "PK_NET_USUARIO" PRIMARY KEY ("ID_USUARIO")
      )
    `);

    await queryRunner.query(`
      ALTER TABLE "NET_USUARIO"
      ADD CONSTRAINT "FK_USUARIO_EMPLEADO" FOREIGN KEY ("ID_EMPLEADO")
      REFERENCES "NET_EMPLEADO" ("ID_EMPLEADO")
    `);

    await queryRunner.query(`
      ALTER TABLE "NET_EVENTOS"
      ADD CONSTRAINT "FK_EVENTO_USUARIO" FOREIGN KEY ("ID_USUARIO")
      REFERENCES "NET_USUARIO" ("ID_USUARIO")
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE "NET_EVENTOS" DROP CONSTRAINT "FK_EVENTO_USUARIO"
    `);

    await queryRunner.query(`
      DROP TABLE "NET_USUARIO"
    `);

    await queryRunner.query(`
      DROP TABLE "NET_EMPLEADO"
    `);
  }
}
