import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateUsuarioRecuperacion20260116113000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "NET_USUARIO_RECUPERACION" (
        "ID_RECUPERACION" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE,
        "TOKEN" VARCHAR2(120) NOT NULL,
        "EXPIRA" TIMESTAMP NOT NULL,
        "UTILIZADO" NUMBER DEFAULT 0 NOT NULL,
        "ID_USUARIO" NUMBER NOT NULL,
        CONSTRAINT "PK_NET_USUARIO_RECUP" PRIMARY KEY ("ID_RECUPERACION")
      )
    `);

    await queryRunner.query(`
      CREATE UNIQUE INDEX "UQ_USUARIO_RECUP_TOKEN" ON "NET_USUARIO_RECUPERACION" ("TOKEN")
    `);

    await queryRunner.query(`
      ALTER TABLE "NET_USUARIO_RECUPERACION"
      ADD CONSTRAINT "FK_RECUP_USUARIO" FOREIGN KEY ("ID_USUARIO")
      REFERENCES "NET_USUARIO" ("ID_USUARIO")
      ON DELETE CASCADE
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE "NET_USUARIO_RECUPERACION"
    `);
  }
}
