import type { Event } from '../types/event';

export const MOCK_EVENTS: Event[] = [
  // TERAPIA OCUPACIONAL
  {
    id: '1',
    title: 'Jornada Recreativa 1',
    description: 'Primera jornada recreativa para el bienestar de los docentes.',
    date: 'Miércoles 17 de diciembre del 2025',
    time: '8:00 a.m. - 4:00 p.m.',
    location: 'Hacienda el Trapiche',
    category: 'Terapia Ocupacional',
    image: 'https://images.unsplash.com/photo-1761456309232-a1416c392687?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    isIntermediate: false,
  },
  {
    id: '2',
    title: 'Jornada Recreativa 2',
    description: 'Segunda jornada recreativa con actividades de integración.',
    date: 'Jueves 18 de diciembre del 2025',
    time: '8:00 a.m. - 4:00 p.m.',
    location: 'Hotel Intercontinental',
    category: 'Terapia Ocupacional',
    image: 'https://images.unsplash.com/photo-1582500347014-3fbe150ed85a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    isIntermediate: false,
  },
  {
    id: '3',
    title: 'Jornada Recreativa 3',
    description: 'Tercera jornada recreativa con dinámicas grupales.',
    date: 'Viernes 19 de diciembre del 2025',
    time: '8:00 a.m. - 4:00 p.m.',
    location: 'Hacienda el Trapiche',
    category: 'Terapia Ocupacional',
    image: 'https://images.unsplash.com/photo-1732023998275-95390af360ee?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    isIntermediate: false,
  },
  {
    id: '4',
    title: 'Encuentro de Terapia Ocupacional',
    description: 'Encuentro profesional de terapia ocupacional con especialistas.',
    date: 'Lunes 22 de diciembre del 2025',
    time: '9:00 a.m. - 5:00 p.m.',
    location: 'Hotel Intercontinental',
    category: 'Terapia Ocupacional',
    image: 'https://images.unsplash.com/photo-1739285452629-2672b13fa42d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    isIntermediate: true,
  },
  {
    id: '5',
    title: 'Adulto Mayor',
    description: 'Jornada especial dedicada al cuidado y bienestar del adulto mayor.',
    date: 'Miércoles 17 de diciembre del 2025',
    time: '8:00 a.m. - 4:00 p.m.',
    location: 'Hacienda el Trapiche',
    category: 'Terapia Ocupacional',
    image: 'https://images.unsplash.com/photo-1761456309232-a1416c392687?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    isIntermediate: false,
  },
  {
    id: '6',
    title: 'Taller de Manualidades',
    description: 'Taller práctico de manualidades y terapia ocupacional.',
    date: 'Jueves 18 de diciembre del 2025',
    time: '9:00 a.m. - 4:00 p.m.',
    location: 'Hotel Intercontinental',
    category: 'Terapia Ocupacional',
    image: 'https://images.unsplash.com/photo-1611257309952-1389bc301a72?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    isIntermediate: false,
  },
  {
    id: '7',
    title: 'Jornada Navideña',
    description: 'Celebración navideña con actividades recreativas.',
    date: 'Miércoles 24 de diciembre del 2025',
    time: '6:00 p.m. - 10:00 p.m.',
    location: 'Hacienda el Trapiche',
    category: 'Terapia Ocupacional',
    image: 'https://images.unsplash.com/photo-1734027851931-6e06637151ed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    isIntermediate: false,
  },
  {
    id: '8',
    title: 'Expo Ventas',
    description: 'Feria de emprendedores locales con productos artesanales.',
    date: 'Viernes 19 de diciembre del 2025',
    time: '9:00 a.m. - 4:00 p.m.',
    location: 'Hacienda el Trapiche',
    category: 'Terapia Ocupacional',
    image: 'https://images.unsplash.com/photo-1719934113502-d2968bc999d7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    isIntermediate: false,
  },
  {
    id: '9',
    title: 'Capacitación para Emprendedores',
    description: 'Programa de formación para desarrollar habilidades empresariales.',
    date: 'Lunes 22 de diciembre del 2025',
    time: '8:00 a.m. - 12:00 p.m.',
    location: 'Hotel Intercontinental',
    category: 'Terapia Ocupacional',
    image: 'https://images.unsplash.com/photo-1719934113502-d2968bc999d7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    isIntermediate: true,
  },
  // PSICOLOGÍA (recortado)
  {
    id: '10',
    title: 'Campamento por la Vida 1',
    description: 'Primera edición del campamento enfocado en el bienestar emocional.',
    date: 'Sábado 20 de diciembre del 2025',
    time: '8:00 a.m. - 6:00 p.m.',
    location: 'Parque Nacional',
    category: 'Psicología',
    image: 'https://images.unsplash.com/photo-1582500347014-3fbe150ed85a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    isIntermediate: false,
  },
];
